# Generated by Django 6.0.8 on 2026-09-07 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_activity_options'),
        ('singer_contest', '0033_score_write_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('judge', 'Judge'), ('scanner', 'Scanner'), ('operational', 'Operational')], max_length=16)),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_points', to='core.activity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entry_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['activity_id', 'kind', 'pk'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('judge', 'Judge'), ('scanner', 'Scanner'), ('operational', 'Operational')], max_length=16)),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='core.activity')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_access_grants', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='singer_contest.contestround')),
                ('entry_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='entry_access.entrypoint')),
            ],
            options={
                'ordering': ['-created_at'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='EphemeralSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('judge', 'Judge'), ('scanner', 'Scanner'), ('operational', 'Operational')], max_length=16)),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ephemeral_sessions', to='core.activity')),
                ('grant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='session', to='entry_access.accessgrant')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ephemeral_sessions', to='singer_contest.contestround')),
            ],
            options={
                'ordering': ['-created_at'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddConstraint(
            model_name='entrypoint',
            constraint=models.UniqueConstraint(fields=('activity', 'kind', 'label'), name='entry_access_unique_entry_point_label'),
        ),
        migrations.AddIndex(
            model_name='accessgrant',
            index=models.Index(fields=['expires_at', 'redeemed_at', 'revoked_at'], name='entry_acces_expires_52f2ff_idx'),
        ),
        migrations.AddIndex(
            model_name='ephemeralsession',
            index=models.Index(fields=['expires_at', 'revoked_at'], name='entry_acces_expires_8bcd47_idx'),
        ),
    ]
