# Generated by Django 6.0.6 on 2026-06-23 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=400)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("singer_contest", "歌手比赛"),
                            ("farewell_show", "毕晚"),
                            ("general", "普通活动"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("testing", "测试/彩排"),
                            ("registration_open", "报名中"),
                            ("registration_closed", "报名截止"),
                            ("reviewing", "审核中"),
                            ("rehearsal", "彩排中"),
                            ("live", "现场进行中"),
                            ("results_pending", "结果整理中"),
                            ("results_published", "结果公示中"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, upload_to="activities/covers/"),
                ),
                ("is_test_mode", models.BooleanField(default=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "activities",
                "ordering": ["-created_at"],
            },
        ),
    ]
