# Generated by Django 6.0.6 on 2026-07-06 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("testing", "测试/彩排"),
                            ("registration_open", "报名中"),
                            ("registration_closed", "报名截止"),
                            ("reviewing", "审核中"),
                            ("rehearsal", "彩排中"),
                            ("live", "现场进行中"),
                            ("results_pending", "结果整理中"),
                            ("results_published", "结果公示中"),
                            ("archived", "已归档"),
                        ],
                        max_length=24,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phase_records",
                        to="core.activity",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "starts_at", "pk"],
                "unique_together": {("activity", "phase")},
            },
        ),
        migrations.CreateModel(
            name="QRCodeLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("registration", "报名入口"),
                            ("vote", "投票入口"),
                            ("results", "结果公示"),
                            ("material_supplement", "材料补交"),
                            ("profile", "个人中心"),
                            ("custom", "自定义"),
                        ],
                        max_length=24,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("target_url", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_links",
                        to="core.activity",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_qr_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["activity", "kind", "pk"],
                "unique_together": {("activity", "kind", "target_url")},
            },
        ),
    ]
