# Generated by Django 6.0.8 on 2026-10-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_activity_public_code_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="judge_entry_open",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="TEST 活动的评委彩排入口是否暂时开放。",
            ),
        ),
    ]
