# Generated by Django 6.0.8 on 2026-10-03 07:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_activity_judge_entry_open"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="public_code",
            field=models.CharField(
                default=core.models.generate_activity_public_code,
                editable=False,
                max_length=8,
                null=True,
                unique=True,
            ),
        ),
    ]
