# Generated by Django 6.0.8 on 2026-10-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_backfill_public_codes_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='judge_entry_version',
            field=models.PositiveIntegerField(default=1, help_text='评委共享二维码的凭证版本。递增即让已发出的那张码立即失效——二维码泄漏时用它重发，而不必关闭整个入口。'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='judge_entry_open',
            field=models.BooleanField(db_default=False, default=False, help_text='评委入口是否暂时开放；关闭后已入席的评委不受影响，新扫描被拒。'),
        ),
    ]
