# Generated by Django 6.0.6 on 2026-06-23 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login", "用户登录"),
                            ("update_registration", "修改报名"),
                            ("update_status", "修改状态"),
                            ("review_material", "审核材料"),
                            ("upload_file", "上传文件"),
                            ("delete_file", "删除文件"),
                            ("enter_score", "录入/修改分数"),
                            ("export", "导出文件"),
                            ("vote_manage", "创建/修改投票"),
                            ("publish_post", "发布/隐藏公开内容"),
                            ("unlock_result", "解锁结果"),
                            ("relock_result", "重新锁定结果"),
                            ("update_permission", "修改用户权限"),
                            ("archive_activity", "归档活动"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=22,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True, help_text="操作对象描述", max_length=200
                    ),
                ),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
