# Generated by Django 6.0.8 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0014_alter_auditlog_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("login", "用户登录"),
                    ("update_registration", "修改报名"),
                    ("update_status", "修改状态"),
                    ("review_material", "审核材料"),
                    ("upload_file", "上传文件"),
                    ("delete_file", "删除文件"),
                    ("enter_score", "录入/修改分数"),
                    ("export", "导出文件"),
                    ("vote_manage", "创建/修改投票"),
                    ("publish_post", "发布/隐藏公开内容"),
                    ("unlock_result", "解锁结果"),
                    ("relock_result", "重新锁定结果"),
                    ("phase_transition", "阶段变更"),
                    ("finalize_advancement", "核定晋级名单"),
                    ("finalize_ruleset", "核定冻结赛制"),
                    ("confirm_stage_result", "核定并锁定赛段结果"),
                    ("unlock_stage_result", "解锁赛段结果"),
                    ("manual_decision", "更新人工选择"),
                    ("duel_decision", "更新对决决定"),
                    ("update_permission", "修改用户权限"),
                    ("initial_admin_provision", "初始化首个管理员"),
                    ("access_grant_issue", "签发临时访问授权"),
                    ("access_grant_redeem", "兑换临时访问授权"),
                    ("access_grant_revoke", "撤销临时访问授权"),
                    ("access_session_revoke", "撤销临时访问会话"),
                    ("ticket_issue", "签发票据"),
                    ("ticket_check_in", "票据检票"),
                    ("ticket_void", "作废票据"),
                    ("ticket_revoke", "撤销票据"),
                    ("ticket_redeem", "兑换票据会话"),
                    ("ticket_session_revoke", "撤销票据会话"),
                    ("judge_panel_prepare", "准备评委组"),
                    ("judge_panel_change", "变更评委组"),
                    ("judge_panel_hold", "暂停评委组"),
                    ("judge_seat_assign", "分配评委席位"),
                    ("judge_seat_revoke", "撤销评委席位"),
                    ("judge_session_issue", "签发评委会话"),
                    ("judge_session_revoke", "撤销评委会话"),
                    ("judge_perf_advance", "推进评委表演"),
                    ("judge_perf_hold", "暂停评委表演"),
                    ("judge_score_submit", "提交评委评分"),
                    ("judge_score_proxy", "代录评委评分"),
                    ("judge_score_paper", "录入纸面评分"),
                    ("archive_activity", "归档活动"),
                    ("unarchive_activity", "解归档活动"),
                    ("release_result", "发布正式结果"),
                    ("revoke_result", "撤销正式结果发布"),
                    ("supersede_result_release", "取代正式结果发布"),
                    ("other", "其他"),
                ],
                default="other",
                max_length=32,
            ),
        ),
    ]
