# Generated by Django 6.0.6 on 2026-06-23 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=400)),
                ("content", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, upload_to="public/covers/"),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("announcement", "通知公告"),
                            ("showcase", "往届风采"),
                            ("activity_review", "活动回顾"),
                            ("registration_entry", "报名入口"),
                            ("voting_entry", "投票入口"),
                            ("result_publication", "结果公示"),
                            ("normal_article", "普通文章"),
                        ],
                        default="normal_article",
                        max_length=22,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("hidden", "已隐藏"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="public_posts",
                        to="core.activity",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "sort_order", "-created_at"],
            },
        ),
    ]
