# Generated by Django 6.0.6 on 2026-06-23 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("public_portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="public/gallery/%Y/%m/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("source_path", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_items",
                        to="public_portal.publicpost",
                    ),
                ),
                (
                    "related_activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="public_media",
                        to="core.activity",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "pk"],
            },
        ),
    ]
