# Generated by Django 6.0.8 on 2026-08-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_portal', '0002_publicmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicpost',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
