# Generated by Django 6.0.8 on 2026-09-21 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_portal', '0003_publicpost_version'),
        ('ruleset', '0015_base_manager_authority'),
        ('singer_contest', '0036_round_minimum_judge_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_version', models.PositiveIntegerField()),
                ('result_version', models.PositiveIntegerField()),
                ('authority_hash', models.CharField(max_length=64)),
                ('input_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', '生效'), ('revoked', '已撤销'), ('superseded', '已被新版本取代')], default='active', max_length=12)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('transition_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_releases', to='public_portal.publicpost')),
                ('released_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_releases', to=settings.AUTH_USER_MODEL)),
                ('ruleset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_releases', to='ruleset.rulesetversion')),
                ('stage_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_releases', to='singer_contest.stageresult')),
                ('transition_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_release_transitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-released_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('post',), name='result_release_one_active_post'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('stage_result',), name='result_release_one_active_stage')],
            },
        ),
    ]
