# Generated by Django 6.0.8 on 2026-10-08 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_backfill_public_codes_again'),
        ('public_portal', '0004_resultrelease'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='publicmedia',
            index=models.Index(fields=['image'], name='publicmedia_image_idx'),
        ),
        migrations.AddIndex(
            model_name='publicpost',
            index=models.Index(fields=['cover_image'], name='publicpost_cover_idx'),
        ),
    ]
