# Generated by Django 6.0.8 on 2026-09-28 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ruleset', '0017_historical_schidui_template_identity'),
        ('singer_contest', '0036_round_minimum_judge_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_key', models.CharField(max_length=64)),
                ('schema_hash', models.CharField(blank=True, max_length=64)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交')], default='draft', max_length=16)),
                ('is_test_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('ruleset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_responses', to='ruleset.rulesetversion')),
                ('singer_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_responses', to='singer_contest.singerregistration')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('singer_registration', 'ruleset_version', 'questionnaire_key'), name='questionnaire_one_response_per_registration_version')],
            },
        ),
    ]
