# Generated by Django 6.0.8 on 2026-10-04 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0001_initial"),
        ("ruleset", "0017_historical_schidui_template_identity"),
        ("singer_contest", "0041_remove_group_group_unique_order_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="questionnaireresponse",
            name="questionnaire_one_response_per_registration_version",
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionnaire_responses",
                to="singer_contest.group",
            ),
        ),
        migrations.AddField(
            model_name="questionnaireresponse",
            name="subject",
            field=models.CharField(
                choices=[("participant", "选手"), ("group", "分组合唱组")],
                default="participant",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="questionnaireresponse",
            name="singer_registration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionnaire_responses",
                to="singer_contest.singerregistration",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionnaireresponse",
            constraint=models.UniqueConstraint(
                condition=models.Q(("singer_registration__isnull", False)),
                fields=("singer_registration", "ruleset_version", "questionnaire_key"),
                name="questionnaire_one_response_per_registration_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionnaireresponse",
            constraint=models.UniqueConstraint(
                condition=models.Q(("group__isnull", False)),
                fields=("group", "ruleset_version", "questionnaire_key"),
                name="questionnaire_one_response_per_group_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionnaireresponse",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("subject", "participant"),
                        ("singer_registration__isnull", False),
                        ("group__isnull", True),
                    ),
                    models.Q(
                        ("subject", "group"),
                        ("singer_registration__isnull", True),
                        ("group__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="questionnaire_subject_owner_xor",
            ),
        ),
    ]
