# Generated by Django 6.0.6 on 2026-06-23 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("song", "歌曲"),
                            ("dance", "舞蹈"),
                            ("instrument", "器乐"),
                            ("drama", "戏剧/小品"),
                            ("recitation", "朗诵"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contact_name", models.CharField(max_length=100)),
                ("contact_phone", models.CharField(max_length=20)),
                ("class_name", models.CharField(max_length=100)),
                ("performers", models.TextField(blank=True)),
                ("estimated_duration", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField(blank=True)),
                ("mic_requirements", models.TextField(blank=True)),
                ("prop_requirements", models.TextField(blank=True)),
                ("special_notes", models.TextField(blank=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("submitted", "已提交"),
                            ("approved", "审核通过"),
                            ("rejected", "审核未通过"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="core.activity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
            },
        ),
    ]
