# Generated by Django 6.0.6 on 2026-06-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farewell_show", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="is_test_data",
            field=models.BooleanField(default=False),
        ),
    ]
