from django.urls import path

from . import views

app_name = "staff"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("activities/", views.activity_list, name="activity_list"),
    path("activities/new/", views.activity_create, name="activity_create"),
    path("activities/<int:pk>/edit/", views.activity_edit, name="activity_edit"),
    path("posts/", views.post_list, name="post_list"),
    path("posts/new/", views.post_create, name="post_create"),
    path("posts/<int:pk>/edit/", views.post_edit, name="post_edit"),
    path("registrations/", views.singer_registration_list, name="singer_registration_list"),
    path(
        "registrations/<int:pk>/",
        views.singer_registration_detail,
        name="singer_registration_detail",
    ),
    path("programs/", views.program_list, name="program_list"),
    path("programs/<int:pk>/", views.program_detail, name="program_detail"),
    path("export/registrations/", views.export_registrations, name="export_registrations"),
    path("export/programs/", views.export_programs, name="export_programs"),
    path("rounds/", views.round_list, name="round_list"),
    path("rounds/new/", views.round_create, name="round_create"),
    path("rounds/<int:pk>/prepare/", views.round_prepare, name="round_prepare"),
    path("rounds/<int:pk>/scores/", views.round_score_entry, name="round_score_entry"),
    path("rounds/<int:pk>/ranking/", views.round_ranking, name="round_ranking"),
    path(
        "rounds/<int:pk>/advancement/",
        views.round_finalize_advancement,
        name="round_finalize_advancement",
    ),
    path("rounds/<int:pk>/lock/", views.round_lock, name="round_lock"),
    path("rounds/<int:pk>/unlock/", views.round_unlock, name="round_unlock"),
    path("rounds/<int:pk>/reset/", views.round_reset, name="round_reset"),
    path("judges/", views.judge_list, name="judge_list"),
    path("judges/new/", views.judge_create, name="judge_create"),
    path("awards/", views.award_list, name="award_list"),
    path("awards/new/", views.award_create, name="award_create"),
    path("vote-sessions/", views.vote_session_list, name="vote_session_list"),
    path("vote-sessions/new/", views.vote_session_create, name="vote_session_create"),
    path("vote-sessions/<int:pk>/", views.vote_session_detail, name="vote_session_detail"),
    path("vote-sessions/<int:pk>/open/", views.vote_session_open, name="vote_session_open"),
    path("vote-sessions/<int:pk>/close/", views.vote_session_close, name="vote_session_close"),
    path("vote-sessions/<int:pk>/lock/", views.vote_session_lock, name="vote_session_lock"),
    path("vote-sessions/<int:pk>/unlock/", views.vote_session_unlock, name="vote_session_unlock"),
    path("vote-sessions/<int:pk>/export/", views.vote_session_export, name="vote_session_export"),
    path("qr/", views.qr_center, name="qr_center"),
    path("qr/<int:pk>/", views.qr_generate, name="qr_generate"),
    path("qr/<int:pk>/<str:kind>.png", views.qr_image, name="qr_image"),
    path("export-center/", views.export_center, name="export_center"),
    path(
        "export/material-checklist/<int:activity_id>/",
        views.excel_material_checklist,
        name="excel_material_checklist",
    ),
    path(
        "export/score-template/<int:round_id>/",
        views.excel_score_template,
        name="excel_score_template",
    ),
    path(
        "export/import-scores/<int:round_id>/",
        views.excel_import_scores,
        name="excel_import_scores",
    ),
    path(
        "word/generate/<int:template_id>/<int:activity_id>/",
        views.word_generate,
        name="word_generate",
    ),
    path("execution-package/<int:activity_id>/", views.execution_package, name="execution_package"),
    path(
        "archive-package/<int:activity_id>/",
        views.archive_package_create,
        name="archive_package_create",
    ),
    path("incidents/", views.incident_list, name="incident_list"),
    path("incidents/new/", views.incident_create, name="incident_create"),
    path("incidents/export/", views.incident_export, name="incident_export"),
    path("activity/<int:pk>/test-toggle/", views.activity_test_toggle, name="activity_test_toggle"),
    path(
        "activity/<int:pk>/clear-test/",
        views.activity_clear_test_data,
        name="activity_clear_test_data",
    ),
    path("activity/<int:pk>/lock/", views.activity_lock, name="activity_lock"),
    path("activity/<int:pk>/unlock/", views.activity_unlock, name="activity_unlock"),
    path("activity/<int:pk>/archive/", views.activity_archive, name="activity_archive"),
    path("activity/<int:pk>/clone/", views.activity_clone, name="activity_clone"),
    path("audit-logs/", views.audit_log_list, name="audit_log_list"),
]
