# Generated by Django 6.0.8 on 2026-08-29 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_activity_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('definition', models.TextField(help_text='JSON ruleset definition (typed node graph).')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('frozen', '已冻结')], default='draft', max_length=12)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruleset_templates', to=settings.AUTH_USER_MODEL)),
                ('frozen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_ruleset_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestRuleset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_test_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_rulesets', to='core.activity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contest_rulesets', to=settings.AUTH_USER_MODEL)),
                ('source_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_rulesets', to='ruleset.rulesettemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RulesetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, help_text='Ruleset instance version counter')),
                ('schema_version', models.PositiveIntegerField(default=1, help_text='Definition schema/ABI version')),
                ('definition', models.TextField(help_text='JSON ruleset definition (typed node graph).')),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('frozen', '已冻结')], default='draft', max_length=12)),
                ('is_current', models.BooleanField(default=True)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ruleset_versions', to=settings.AUTH_USER_MODEL)),
                ('frozen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_ruleset_versions', to=settings.AUTH_USER_MODEL)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ruleset.contestruleset')),
            ],
            options={
                'ordering': ['-version', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('ruleset', 'version'), name='rulesetversion_unique_version_per_ruleset'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('ruleset',), name='rulesetversion_one_current_per_ruleset')],
            },
        ),
    ]
