# Generated by Django 6.0.8 on 2026-08-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesetversion',
            name='execution_plan',
            field=models.TextField(blank=True, editable=False, help_text='Canonical JSON ExecutionPlan persisted at freeze.'),
        ),
    ]
