# Generated by Django 6.0.8 on 2026-08-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleset', '0002_rulesetversion_execution_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestruleset',
            name='announcement_blocks',
            field=models.JSONField(blank=True, default=list, help_text='Handcard announcement blocks: list of {label, outcome_codes} for the result board.'),
        ),
        migrations.AddField(
            model_name='contestruleset',
            name='round_keys',
            field=models.JSONField(blank=True, default=dict, help_text="Maps a ruleset round key to a ContestRound pk, e.g. {'r1': 3, 'r2': 5}."),
        ),
        migrations.AddField(
            model_name='contestruleset',
            name='stage_key',
            field=models.CharField(blank=True, help_text="Bindable stage identifier, e.g. '院十佳'; drives auto re-resolve.", max_length=100),
        ),
    ]
