# Generated by Django 6.0.8 on 2026-08-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleset', '0003_contestruleset_announcement_blocks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestruleset',
            name='announcement_blocks',
            field=models.JSONField(blank=True, default=list, help_text='Handcard blocks: list of {label, outcome_codes} for the result board.'),
        ),
    ]
