# Generated by Django 6.0.8 on 2026-08-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleset', '0004_alter_contestruleset_announcement_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesetversion',
            name='binding',
            field=models.JSONField(blank=True, default=dict, help_text='Freeze-time binding snapshot: {stage_key, round_keys, announcement_blocks}.'),
        ),
    ]
