# Generated by Django 6.0.8 on 2026-08-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleset', '0006_backfill_frozen_binding'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestruleset',
            name='group_keys',
            field=models.JSONField(blank=True, default=dict, help_text="Maps a group 'by' key to a ContestRound pk, e.g. {'initial_group': 3}."),
        ),
        migrations.AddField(
            model_name='contestruleset',
            name='vote_keys',
            field=models.JSONField(blank=True, default=dict, help_text="Maps a ruleset vote_source key to a VoteSession pk, e.g. {'audience1': 7}."),
        ),
    ]
