# Generated by Django 6.0.8 on 2026-08-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleset', '0007_contestruleset_group_keys_contestruleset_vote_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesetversion',
            name='authority_hash',
            field=models.CharField(blank=True, help_text='sha256 of definition + frozen binding + plan version; the authority digest.', max_length=64),
        ),
    ]
