# Generated by Django 6.0.8 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ruleset", "0008_rulesetversion_authority_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestruleset",
            name="announcement_blocks_by_checkpoint",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Checkpoint-specific handcard blocks: {checkpoint_key: [{label, "
                    "outcome_codes}, ...]}. Overrides announcement_blocks for that stage."
                ),
            ),
        ),
    ]
