# Generated by Django 6.0.8 on 2026-08-31 15:23

from django.conf import settings
from django.db import migrations, models


def _demote_non_frozen_current(apps, schema_editor):
    """Demote a historical is_current row that is not FROZEN (M1-R9 §四).

    ``is_current`` defaulted to True, so a bare ``create()`` could mint a "Draft
    official authority" (is_current=True, status=draft) that shadowed the next real
    freeze's partial-unique and injected false authority. A current row that is not
    ``frozen`` is invalid; only a current-and-frozen row is the legitimate (single,
    by partial-unique) official authority and is left untouched.
    """
    RulesetVersion = apps.get_model("ruleset", "RulesetVersion")
    RulesetVersion.objects.filter(is_current=True).exclude(status="frozen").update(
        is_current=False
    )


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ruleset', '0009_contestruleset_announcement_blocks_by_checkpoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesetversion',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(_demote_non_frozen_current, _noop),
        migrations.AddConstraint(
            model_name='rulesetversion',
            constraint=models.CheckConstraint(condition=models.Q(('is_current', False), ('status', 'frozen'), _connector='OR'), name='rulesetversion_current_implies_frozen'),
        ),
    ]
