# Generated by Django 6.0.8 on 2026-09-01 02:52

from django.conf import settings
from django.db import migrations, models


def _dedupe_contest_rulesets(apps, schema_editor):
    """M1-R9-Final: an activity owns exactly one ContestRuleset authority.

    Re-parent a duplicate ruleset's versions onto the canonical ruleset (the one owning the
    most-recent current-FROZEN version, else the lowest pk), then drop the empty duplicate.
    A re-parent that would collide on (ruleset, version) aborts loudly — pre-production fail,
    not silent data loss.
    """
    ContestRuleset = apps.get_model("ruleset", "ContestRuleset")
    RulesetVersion = apps.get_model("ruleset", "RulesetVersion")

    for activity_id in ContestRuleset.objects.values_list("activity_id", flat=True).distinct():
        rulesets = list(ContestRuleset.objects.filter(activity_id=activity_id).order_by("pk"))
        if len(rulesets) <= 1:
            continue

        canonical = None
        newest = None
        for rs in rulesets:
            current = RulesetVersion.objects.filter(ruleset_id=rs.pk, is_current=True).order_by("-pk").first()
            if current is not None and (newest is None or current.pk > newest.pk):
                newest, canonical = current, rs
        if canonical is None:
            canonical = rulesets[0]

        for dup in rulesets:
            if dup.pk == canonical.pk:
                continue
            for version in RulesetVersion.objects.filter(ruleset_id=dup.pk).order_by("version", "pk"):
                if RulesetVersion.objects.filter(ruleset_id=canonical.pk, version=version.version).exists():
                    raise ValueError(
                        f"re-parent RulesetVersion {version.pk} to ContestRuleset {canonical.pk} "
                        f"would collide on version {version.version}"
                    )
                RulesetVersion._base_manager.filter(pk=version.pk).update(ruleset_id=canonical.pk)
            ContestRuleset._base_manager.filter(pk=dup.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_activity_options'),
        ('ruleset', '0010_alter_rulesetversion_is_current_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_dedupe_contest_rulesets, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='contestruleset',
            constraint=models.UniqueConstraint(fields=('activity',), name='contest_ruleset_unique_activity'),
        ),
    ]
