# Generated by Django 6.0.8 on 2026-09-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleset', '0011_contestruleset_contest_ruleset_unique_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestruleset',
            name='audience_keys',
            field=models.JSONField(blank=True, default=dict, help_text="Maps a ruleset audience vote_source key to an AudienceScore stage_key grouping, e.g. {'aud1': 'stage1'}."),
        ),
    ]
