# Generated by Django 6.0.8 on 2026-09-04 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruleset', '0014_rulesettemplate_capability_truth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rulesetversion',
            options={'base_manager_name': 'objects', 'ordering': ['-version', 'pk']},
        ),
    ]
