# Generated by Django 6.0.8 on 2026-09-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleset', '0015_base_manager_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestruleset',
            name='vote_scoring_rule_keys',
            field=models.JSONField(blank=True, default=dict, help_text="Maps a ruleset vote_source key to the VoteScoringRule pk that converts its ballots into a score, e.g. {'audience1': 4}. The frozen binding snapshots the rule id, mode and output scale."),
        ),
    ]
