# Generated by Django 6.0.8 on 2026-10-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ruleset", "0017_historical_schidui_template_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestruleset",
            name="group_stage_keys",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Maps a Group Chorus 'by' key to a frozen GroupStage pk.",
            ),
        ),
    ]
