# Generated by Django 6.0.8 on 2026-09-05 02:43

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_reconcile_staff_flag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.models.UserAuthorityManager()),
            ],
        ),
    ]
