# Generated by Django 6.0.8 on 2026-09-24

from django.db import migrations, models
from django.db.models import Q
from django.utils import timezone


def initialize_installation_state(apps, schema_editor):
    del schema_editor
    installation_state = apps.get_model("accounts", "InstallationState")
    user = apps.get_model("accounts", "User")
    has_effective_admin = user.objects.filter(is_active=True).filter(
        Q(role="admin") | Q(is_superuser=True)
    ).exists()
    installation_state.objects.create(
        pk=1,
        initialized_at=timezone.now() if has_effective_admin else None,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_options_alter_user_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstallationState",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("initialized_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "installation state",
                "verbose_name_plural": "installation state",
            },
        ),
        migrations.RunPython(initialize_installation_state, migrations.RunPython.noop),
    ]
