# Generated by Django 6.0.6 on 2026-06-23 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("singer_contest", "0002_award_contestround_judge_scorerecord_scoresummary"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoteSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("passcode", models.CharField(max_length=20)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_open", models.BooleanField(default=False)),
                ("is_locked", models.BooleanField(default=False)),
                (
                    "selection_type",
                    models.CharField(
                        choices=[("single", "单选"), ("multi", "多选")],
                        default="single",
                        max_length=8,
                    ),
                ),
                ("max_selections", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_sessions",
                        to="core.activity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoteOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "singer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_options",
                        to="singer_contest.singerregistration",
                    ),
                ),
                (
                    "vote_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="voting.votesession",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "pk"],
                "unique_together": {("vote_session", "singer")},
            },
        ),
        migrations.CreateModel(
            name="VoteRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("browser_session_key", models.CharField(max_length=64)),
                ("ip_address", models.GenericIPAddressField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vote_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="voting.voteoption",
                    ),
                ),
                (
                    "vote_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="voting.votesession",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("vote_session", "browser_session_key", "vote_option")
                },
            },
        ),
    ]
