# Generated by Django 6.0.6 on 2026-08-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_votesession_is_test_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteoption',
            name='is_test_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voterecord',
            name='is_test_data',
            field=models.BooleanField(default=False),
        ),
    ]
