# Generated by Django 6.0.8 on 2026-08-27 14:21

import django.db.models.deletion
from django.db import migrations, models


def migrate_records_to_ballots(apps, schema_editor):
    VoteBallot = apps.get_model("voting", "VoteBallot")
    VoteRecord = apps.get_model("voting", "VoteRecord")
    ballots = {}
    for record in VoteRecord.objects.order_by("pk"):
        key = (record.vote_session_id, record.browser_session_key)
        ballot = ballots.get(key)
        if ballot is None:
            ballot = VoteBallot.objects.create(
                vote_session_id=record.vote_session_id,
                browser_session_key=record.browser_session_key,
                ip_address=record.ip_address,
                is_test_data=record.is_test_data,
            )
            ballots[key] = ballot
        record.ballot_id = ballot.pk
        record.save(update_fields=["ballot"])


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_voteoption_is_test_data_voterecord_is_test_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteBallot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_session_key', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField()),
                ('is_test_data', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('vote_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='voting.votesession')),
            ],
        ),
        migrations.AddField(
            model_name='voterecord',
            name='ballot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='voting.voteballot'),
        ),
        migrations.RunPython(migrate_records_to_ballots, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='voterecord',
            constraint=models.UniqueConstraint(condition=models.Q(('ballot__isnull', False)), fields=('ballot', 'vote_option'), name='voting_one_choice_per_ballot_option'),
        ),
        migrations.AddConstraint(
            model_name='voteballot',
            constraint=models.UniqueConstraint(fields=('vote_session', 'browser_session_key'), name='voting_one_ballot_per_browser_session'),
        ),
    ]
