# Generated by Django 6.0.8 on 2026-08-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_activity_options'),
        ('voting', '0004_voteballot_voterecord_ballot_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='votesession',
            constraint=models.CheckConstraint(condition=models.Q(('is_locked', True), ('is_open', True), _negated=True), name='vote_locked_must_be_closed'),
        ),
        migrations.AddConstraint(
            model_name='votesession',
            constraint=models.CheckConstraint(condition=models.Q(('max_selections__gte', 1)), name='vote_max_selections_positive'),
        ),
        migrations.AddConstraint(
            model_name='votesession',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='vote_end_after_start'),
        ),
    ]
