# Generated by Django 6.0.8 on 2026-09-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_votesession_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voteballot',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='voteoption',
            options={'base_manager_name': 'objects', 'ordering': ['sort_order', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='voterecord',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='votesession',
            options={'base_manager_name': 'objects', 'ordering': ['-created_at']},
        ),
    ]
