# Generated by Django 6.0.8 on 2026-09-08 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        ('voting', '0007_m1_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteballot',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='votesession',
            name='requires_ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='voteballot',
            constraint=models.UniqueConstraint(condition=models.Q(('ticket__isnull', False)), fields=('vote_session', 'ticket'), name='voting_one_ballot_per_ticket_session'),
        ),
    ]
