# Generated by Django 6.0.8 on 2026-09-27 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_voteballot_ticket_votesession_requires_ticket_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='votesession',
            name='purpose',
            field=models.CharField(choices=[('selection', '晋级/选择'), ('popularity', '人气奖'), ('repechage', '复活'), ('score_component', '成绩组成')], default='selection', max_length=16),
        ),
        migrations.CreateModel(
            name='VoteScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('ballot_share_percent', '有效票支持率（0-100）')], default='ballot_share_percent', max_length=32)),
                ('output_scale', models.CharField(default='hundred', help_text='结果量纲：支持率为 0-100 分制。', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote_scoring_rules', to=settings.AUTH_USER_MODEL)),
                ('vote_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rule', to='voting.votesession')),
            ],
            options={
                'ordering': ['vote_session_id'],
                'base_manager_name': 'objects',
            },
        ),
    ]
