# Generated by Django 6.0.8 on 2026-10-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticket_recoverable_credential"),
        ("voting", "0011_alter_votesession_passcode"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="voteballot",
            name="voting_one_ballot_per_browser_session",
        ),
        migrations.AddConstraint(
            model_name="voteballot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ticket__isnull", True)),
                fields=("vote_session", "browser_session_key"),
                name="voting_one_ballot_per_browser_session",
            ),
        ),
    ]
