# Generated by Django 6.0.8 on 2026-10-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0012_ballot_browser_uniqueness_requires_no_ticket"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="voterecord",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="voterecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ballot__isnull", True)),
                fields=("vote_session", "browser_session_key", "vote_option"),
                name="voting_one_legacy_record_per_browser_option",
            ),
        ),
    ]
