# Generated by Django 6.0.6 on 2026-06-23 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("singer_registration", "歌手比赛报名开启"),
                            ("preliminary_notice", "初赛通知"),
                            ("semi_final_notice", "复赛通知"),
                            ("award_result", "获奖名单公示"),
                            ("vote_guide", "观众投票说明"),
                            ("program_collection", "毕晚节目征集"),
                            ("program_list_publish", "毕晚节目单发布"),
                            ("farewell_review", "毕晚活动回顾"),
                            ("rehearsal_notice", "彩排通知"),
                        ],
                        max_length=22,
                        unique=True,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="正文，用 {title}, {subtitle}, {date}, {time}, {venue}, {content}, {sign_off} 等占位符"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExportTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("registration_list", "报名名单"),
                            ("contact_list", "联系方式表"),
                            ("material_checklist", "材料清单"),
                            ("program_list", "节目单"),
                            ("score_template", "评分表模板"),
                            ("preliminary_result", "初赛成绩"),
                            ("semi_final_result", "复赛成绩"),
                            ("final_ranking", "最终排名"),
                            ("advancement_list", "晋级名单"),
                            ("vote_result", "投票结果"),
                            ("award_list", "获奖名单"),
                            ("incident_list", "异常记录"),
                        ],
                        max_length=22,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("xlsx", "Excel"), ("docx", "Word")],
                        default="xlsx",
                        max_length=4,
                    ),
                ),
                ("file", models.FileField(blank=True, upload_to="exports/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_tasks",
                        to="core.activity",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("file", models.FileField(upload_to="generated/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_docs",
                        to="core.activity",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_docs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="exports.articletemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
