# Generated by Django 6.0.8 on 2026-10-08 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_backfill_public_codes_again'),
        ('exports', '0002_generated_document_test_marker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exporttask',
            index=models.Index(fields=['file'], name='exporttask_file_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['file'], name='generateddocument_file_idx'),
        ),
    ]
