# Generated by Django 6.0.6 on 2026-06-23 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SingerRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("student_id", models.CharField(max_length=20)),
                ("college", models.CharField(max_length=100)),
                ("class_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("wechat", models.CharField(blank=True, max_length=50)),
                ("song_name", models.CharField(max_length=200)),
                ("is_original", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("remark", models.TextField(blank=True)),
                (
                    "pre_status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("submitted", "已提交"),
                            ("need_supplement", "资料待补充"),
                            ("approved", "审核通过"),
                            ("rejected", "审核未通过"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "live_status",
                    models.CharField(
                        choices=[
                            ("not_checked_in", "未签到"),
                            ("checked_in", "已签到"),
                            ("waiting", "已候场"),
                            ("performed", "已表演"),
                            ("waiting_score", "待录分"),
                            ("scored", "已录分"),
                            ("score_reviewed", "成绩已复核"),
                            ("advanced", "已晋级"),
                            ("not_advanced", "未晋级"),
                            ("abandoned", "弃赛"),
                            ("delayed", "延后出场"),
                        ],
                        default="not_checked_in",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="singer_registrations",
                        to="core.activity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="singer_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
