# Generated by Django 6.0.6 on 2026-06-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("singer_contest", "0002_award_contestround_judge_scorerecord_scoresummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="award",
            name="is_test_data",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scorerecord",
            name="is_test_data",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scoresummary",
            name="is_test_data",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="singerregistration",
            name="is_test_data",
            field=models.BooleanField(default=False),
        ),
    ]
