# Generated by Django 6.0.8 on 2026-08-27 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer_contest', '0003_award_is_test_data_scorerecord_is_test_data_and_more'),
        ('voting', '0004_voteballot_voterecord_ballot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='source_vote_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_popularity_award', to='voting.votesession'),
        ),
    ]
