# Generated by Django 6.0.8 on 2026-08-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("singer_contest", "0004_award_source_vote_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestround",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("prepared", "已准备"),
                    ("scoring", "评分中"),
                    ("locked", "已锁定"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="RoundEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="singer_contest.contestround",
                    ),
                ),
                (
                    "singer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_entries",
                        to="singer_contest.singerregistration",
                    ),
                ),
            ],
            options={
                "unique_together": {("round", "singer")},
            },
        ),
        migrations.CreateModel(
            name="RoundJudge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_assignments",
                        to="singer_contest.judge",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_judges",
                        to="singer_contest.contestround",
                    ),
                ),
            ],
            options={
                "unique_together": {("round", "judge")},
            },
        ),
    ]
