# Generated by Django 6.0.8 on 2026-08-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("singer_contest", "0005_round_snapshot_and_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roundentry",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entries",
                to="singer_contest.contestround",
            ),
        ),
        migrations.AlterField(
            model_name="roundentry",
            name="singer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="round_entries",
                to="singer_contest.singerregistration",
            ),
        ),
        migrations.AlterField(
            model_name="roundjudge",
            name="judge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="round_assignments",
                to="singer_contest.judge",
            ),
        ),
        migrations.AlterField(
            model_name="roundjudge",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="round_judges",
                to="singer_contest.contestround",
            ),
        ),
    ]
