# Generated by Django 6.0.8 on 2026-08-28

import singer_contest.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("singer_contest", "0006_protect_round_snapshots"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roundentry",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="roundjudge",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterField(
            model_name="roundentry",
            name="round",
            field=models.ForeignKey(
                on_delete=singer_contest.deletion.cascade_draft_snapshots_or_protect_prepared,
                related_name="entries",
                to="singer_contest.contestround",
            ),
        ),
        migrations.AlterField(
            model_name="roundentry",
            name="singer",
            field=models.ForeignKey(
                on_delete=singer_contest.deletion.cascade_draft_snapshots_or_protect_prepared,
                related_name="round_entries",
                to="singer_contest.singerregistration",
            ),
        ),
        migrations.AlterField(
            model_name="roundjudge",
            name="judge",
            field=models.ForeignKey(
                on_delete=singer_contest.deletion.cascade_draft_snapshots_or_protect_prepared,
                related_name="round_assignments",
                to="singer_contest.judge",
            ),
        ),
        migrations.AlterField(
            model_name="roundjudge",
            name="round",
            field=models.ForeignKey(
                on_delete=singer_contest.deletion.cascade_draft_snapshots_or_protect_prepared,
                related_name="round_judges",
                to="singer_contest.contestround",
            ),
        ),
    ]
