# Generated by Django 6.0.8 on 2026-08-28 05:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_activity_options'),
        ('singer_contest', '0007_alter_roundentry_options_alter_roundjudge_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='singerregistration',
            constraint=models.UniqueConstraint(fields=('activity', 'user'), name='singer_one_registration_per_account_per_activity'),
        ),
        migrations.AddConstraint(
            model_name='singerregistration',
            constraint=models.UniqueConstraint(fields=('activity', 'student_id'), name='singer_one_registration_per_student_per_activity'),
        ),
    ]
