# Generated by Django 6.0.8 on 2026-08-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_activity_options'),
        ('singer_contest', '0008_singerregistration_singer_one_registration_per_account_per_activity_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contestround',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_locked', True), ('status', 'locked')), models.Q(models.Q(('status', 'locked'), _negated=True), ('is_locked', False)), _connector='OR'), name='round_status_lock_consistent'),
        ),
        migrations.AddConstraint(
            model_name='contestround',
            constraint=models.CheckConstraint(condition=models.Q(('advance_count__gte', 0)), name='round_advance_count_non_negative'),
        ),
    ]
