# Generated by Django 6.0.8 on 2026-08-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer_contest', '0009_contestround_round_status_lock_consistent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestround',
            name='advancement_status',
            field=models.CharField(choices=[('auto', '自动晋级'), ('needs_review', '待人工核定'), ('finalized', '已核定晋级')], default='auto', max_length=16),
        ),
    ]
