# Generated by Django 6.0.8 on 2026-08-29 07:15

import django.db.models.deletion
from django.db import migrations, models


def backfill_round_sequence(apps, schema_editor):
    ContestRound = apps.get_model("singer_contest", "ContestRound")
    round_order = {"preliminary": 0, "semi_final": 1}
    for activity_id in ContestRound.objects.values_list("activity_id", flat=True).distinct():
        rounds = list(ContestRound.objects.filter(activity_id=activity_id).order_by("pk"))
        ordered = sorted(rounds, key=lambda r: (round_order.get(r.round_type, 2), r.pk))
        for sequence, contest_round in enumerate(ordered, start=1):
            ContestRound.objects.filter(pk=contest_round.pk).update(sequence=sequence)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_activity_options'),
        ('singer_contest', '0010_contestround_advancement_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contestround',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contestround',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestround',
            name='sequence',
            field=models.PositiveIntegerField(default=1, help_text='同一活动内的轮次顺序'),
        ),
        migrations.RunPython(backfill_round_sequence, migrations.RunPython.noop),
        migrations.AddField(
            model_name='contestround',
            name='venue',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='PerformanceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_test_data', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_groups', to='core.activity')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='singer_contest.contestround')),
            ],
            options={
                'ordering': ['sequence', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ScoringRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_test_data', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='core.activity')),
            ],
            options={
                'ordering': ['sequence', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('is_test_data', models.BooleanField(default=False)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='singer_contest.scoringrubric')),
            ],
            options={
                'ordering': ['sequence', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='contestround',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds', to='singer_contest.scoringrubric'),
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('song_title', models.CharField(blank=True, max_length=200)),
                ('guest', models.CharField(blank=True, help_text='助演/合作嘉宾', max_length=100)),
                ('duration', models.DurationField(blank=True, help_text='演出时长', null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_test_data', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='core.activity')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='singer_contest.contestround')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='singer_contest.singerregistration')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='singer_contest.performancegroup')),
            ],
            options={
                'ordering': ['sequence', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('round', 'singer'), name='performance_one_per_round_per_singer')],
            },
        ),
        migrations.CreateModel(
            name='CriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_test_data', models.BooleanField(default=False)),
                ('score_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to='singer_contest.scorerecord')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='singer_contest.rubriccriterion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('score_record', 'criterion'), name='criterion_score_unique_per_record_criterion')],
            },
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.UniqueConstraint(fields=('rubric', 'name'), name='rubric_criterion_unique_name'),
        ),
    ]
