# Generated by Django 6.0.8 on 2026-08-29 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_activity_options'),
        ('ruleset', '0002_rulesetversion_execution_plan'),
        ('singer_contest', '0011_alter_contestround_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_key', models.CharField(help_text="Bindable stage identifier, e.g. '院十佳'.", max_length=100)),
                ('status', models.CharField(choices=[('hold', '待齐数据'), ('review', '待人工核定'), ('ready', '可发布')], default='hold', max_length=16)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('plan_version', models.PositiveIntegerField(default=0)),
                ('result_version', models.PositiveIntegerField(default=1)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('is_test_data', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_results', to='core.activity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_results', to=settings.AUTH_USER_MODEL)),
                ('ruleset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_results', to='ruleset.rulesetversion')),
            ],
            options={
                'ordering': ['-computed_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='StageDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_code', models.CharField(choices=[('direct', 'direct'), ('advanced', 'advanced'), ('repechage', 'repechage'), ('pending', 'pending'), ('eliminated', 'eliminated'), ('wildcard', 'wildcard'), ('finalist', 'finalist')], max_length=20)),
                ('source_node', models.CharField(blank=True, max_length=100)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('reason', models.TextField(blank=True)),
                ('is_test_data', models.BooleanField(default=False)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_decisions', to='singer_contest.singerregistration')),
                ('stage_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='singer_contest.stageresult')),
            ],
            options={
                'ordering': ['stage_result', 'rank', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CompositeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_key', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=6, max_digits=14)),
                ('components', models.JSONField(blank=True, default=list)),
                ('is_test_data', models.BooleanField(default=False)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_composites', to='singer_contest.singerregistration')),
                ('stage_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composites', to='singer_contest.stageresult')),
            ],
            options={
                'ordering': ['stage_result', 'node_key', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='stageresult',
            constraint=models.UniqueConstraint(fields=('activity', 'stage_key', 'content_hash'), name='stage_result_unique_per_activity_stage_hash'),
        ),
        migrations.AddConstraint(
            model_name='stagedecision',
            constraint=models.UniqueConstraint(fields=('stage_result', 'singer'), name='stage_decision_one_per_result_singer'),
        ),
        migrations.AddConstraint(
            model_name='compositeresult',
            constraint=models.UniqueConstraint(fields=('stage_result', 'singer', 'node_key'), name='composite_one_per_result_singer_node'),
        ),
    ]
