# Generated by Django 6.0.8 on 2026-08-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer_contest', '0012_stageresult_stagedecision_compositeresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestround',
            name='score_version',
            field=models.PositiveIntegerField(default=0, help_text='Bumped on every applied score change (stale-edit detection).'),
        ),
    ]
