# Generated by Django 6.0.8 on 2026-08-31 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def map_legacy_ready_to_confirmed(apps, schema_editor):
    # Pre-split status "ready" meant "published and locked". The split (§36-37)
    # reserves "ready_to_confirm" for machine-computed (still mutable) results, so a
    # legacy published row must become CONFIRMED to stay immutable.
    StageResult = apps.get_model("singer_contest", "StageResult")
    StageResult.objects.filter(status="ready").update(status="confirmed")


class Migration(migrations.Migration):
    dependencies = [
        ("singer_contest", "0014_stageresult_result_identity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stageresult",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True, help_text="When a staff member 核定并锁定 the result.", null=True
            ),
        ),
        migrations.AddField(
            model_name="stageresult",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_stage_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stageresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("hold", "待齐数据"),
                    ("review", "待人工核定"),
                    ("ready_to_confirm", "待核定"),
                    ("confirmed", "已核定"),
                ],
                default="hold",
                max_length=16,
            ),
        ),
        migrations.RunPython(map_legacy_ready_to_confirmed, migrations.RunPython.noop),
    ]
