# Generated by Django 6.0.8 on 2026-08-31 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_activity_options'),
        ('ruleset', '0007_contestruleset_group_keys_contestruleset_vote_keys'),
        ('singer_contest', '0015_stageresult_confirmed_at_stageresult_confirmed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_key', models.CharField(help_text="The MANUAL_SELECT node key, e.g. 'manual'.", max_length=100)),
                ('group', models.CharField(blank=True, help_text="Group name; '' for a non-group (flat) manual source.", max_length=100)),
                ('chosen', models.JSONField(default=list, help_text='Ordered SingerRegistration pk strings picked into this group.')),
                ('is_test_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_decisions', to='core.activity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_decisions', to=settings.AUTH_USER_MODEL)),
                ('ruleset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_decisions', to='ruleset.rulesetversion')),
            ],
            options={
                'unique_together': {('ruleset_version', 'manual_key', 'group')},
            },
        ),
    ]
