# Generated by Django 6.0.8 on 2026-09-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer_contest', '0019_remove_stageresult_stage_result_unique_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestround',
            name='roster_source',
            field=models.CharField(choices=[('approved', '批准名单'), ('stage', '赛段晋级'), ('legacy', '上一轮晋级')], default='approved', max_length=16),
        ),
        migrations.AddField(
            model_name='contestround',
            name='roster_source_stage',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
