# Generated by Django 6.0.8 on 2026-09-02 13:06

from django.db import migrations, models


def backfill_semifinal_legacy(apps, schema_editor):
    # The 0020 field defaulted roster_source to 'approved', which the old
    # effective_roster_source() treated as "auto -> derive LEGACY for a SEMI_FINAL".
    # Now that '' means auto, an existing SEMI_FINAL pinned to 'approved' must be
    # pinned to 'legacy' explicitly to keep its intended (derived) behaviour.
    ContestRound = apps.get_model("singer_contest", "ContestRound")
    ContestRound.objects.filter(
        round_type="semi_final", roster_source="approved"
    ).update(roster_source="legacy")


class Migration(migrations.Migration):

    dependencies = [
        ('singer_contest', '0020_contestround_roster_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestround',
            name='roster_source',
            field=models.CharField(blank=True, choices=[('approved', '批准名单'), ('stage', '赛段晋级'), ('legacy', '上一轮晋级')], default='', help_text='晋级名单来源；置空时按轮次类型自动判定。', max_length=16),
        ),
        migrations.RunPython(backfill_semifinal_legacy, migrations.RunPython.noop),
    ]
