# Generated by Django 6.0.8 on 2026-09-02 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_activity_options'),
        ('singer_contest', '0021_alter_contestround_roster_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_key', models.CharField(help_text="Audience-set name grouped in the binding's audience_keys.", max_length=100)),
                ('score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_test_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_scores', to='core.activity')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audience_scores', to=settings.AUTH_USER_MODEL)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_scores', to='singer_contest.singerregistration')),
            ],
            options={
                'ordering': ['stage_key', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('activity', 'stage_key', 'singer'), name='ux_audience_activity_stage_singer')],
            },
        ),
    ]
