# Generated by Django 6.0.8 on 2026-09-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singer_contest', '0029_round_sequence_authority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiencescore',
            options={'base_manager_name': 'objects', 'ordering': ['stage_key', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='award',
            options={'base_manager_name': 'objects', 'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='compositeresult',
            options={'base_manager_name': 'objects', 'ordering': ['stage_result', 'node_key', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='contestround',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='criterionscore',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={'base_manager_name': 'objects', 'ordering': ['sequence', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='performancegroup',
            options={'base_manager_name': 'objects', 'ordering': ['sequence', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='rubriccriterion',
            options={'base_manager_name': 'objects', 'ordering': ['sequence', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='scorerecord',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='scoresummary',
            options={'base_manager_name': 'objects', 'ordering': ['-average_score']},
        ),
        migrations.AlterModelOptions(
            name='scoringrubric',
            options={'base_manager_name': 'objects', 'ordering': ['sequence', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='stageawarddecision',
            options={'base_manager_name': 'objects', 'ordering': ['stage_result', 'name', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='stagedecision',
            options={'base_manager_name': 'objects', 'ordering': ['stage_result', 'rank', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='stageresult',
            options={'base_manager_name': 'objects', 'ordering': ['-computed_at', 'pk']},
        ),
    ]
