# Generated by Django 6.0.8 on 2026-09-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singer_contest', '0030_m1_authority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dueldecision',
            options={'base_manager_name': 'objects', 'ordering': ['duel_key', 'pair_key', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='manualdecision',
            options={'base_manager_name': 'objects'},
        ),
    ]
