# Generated by Django 6.0.8 on 2026-09-05 02:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("singer_contest", "0031_m1_authority_followup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="judge",
            options={"base_manager_name": "objects", "ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="singerregistration",
            options={"base_manager_name": "objects", "ordering": ["-created_at"]},
        ),
    ]
