# Generated by Django 6.0.8 on 2026-09-05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("singer_contest", "0032_alter_judge_options_alter_singerregistration_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreWriteReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("command_id", models.CharField(max_length=64, unique=True)),
                ("operation", models.CharField(max_length=64)),
                ("payload_hash", models.CharField(max_length=64)),
                ("result_version", models.PositiveIntegerField()),
                ("result_payload", models.JSONField(default=dict)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("succeeded", "Succeeded")], default="pending", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("operator", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="score_write_receipts", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "base_manager_name": "objects",
            },
        ),
    ]
