# Generated by Django 6.0.8 on 2026-09-08 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_activity_options'),
        ('entry_access', '0001_initial'),
        ('singer_contest', '0033_score_write_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('assigned', 'Assigned'), ('revoked', 'Revoked'), ('hold', 'Hold')], max_length=16)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=240)),
                ('is_test_data', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_judge_seats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='RoundPanelSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('change_policy', models.CharField(choices=[('hold_only', 'Hold only'), ('versioned_replacement', 'Versioned replacement')], max_length=24)),
                ('state', models.CharField(choices=[('active', 'Active'), ('hold', 'Hold'), ('superseded', 'Superseded')], max_length=16)),
                ('expected_judge_count', models.PositiveIntegerField()),
                ('minimum_judge_count', models.PositiveIntegerField()),
                ('scoring_method', models.CharField(max_length=32)),
                ('roster_digest', models.CharField(max_length=64)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('is_test_data', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='judge_panel_snapshots', to='core.activity')),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_judge_panel_snapshots', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='judge_panel_snapshots', to='singer_contest.contestround')),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='JudgeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('is_test_data', models.BooleanField(default=False)),
                ('ephemeral_session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='judge_session', to='entry_access.ephemeralsession')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='singer_contest.judgeseat')),
                ('panel_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='judge_sessions', to='singer_contest.roundpanelsnapshot')),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='JudgeSeatGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_grant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='judge_seat_grant', to='entry_access.accessgrant')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='singer_contest.judgeseat')),
                ('panel_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_grants', to='singer_contest.roundpanelsnapshot')),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='RoundPanelSnapshotMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_key', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panel_snapshot_members', to='singer_contest.judge')),
                ('panel_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='singer_contest.roundpanelsnapshot')),
                ('source_round_judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panel_snapshot_members', to='singer_contest.roundjudge')),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='judgeseat',
            name='panel_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seats', to='singer_contest.roundpanelsnapshotmember'),
        ),
        migrations.CreateModel(
            name='PerformanceRunState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('performing', 'Performing'), ('accepting_score', 'Accepting score'), ('hold', 'Hold'), ('closed', 'Closed')], max_length=24)),
                ('context_version', models.PositiveIntegerField(default=0)),
                ('hold_reason', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_test_data', models.BooleanField(default=False)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_performance_run_states', to=settings.AUTH_USER_MODEL)),
                ('current_performance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_run_states', to='singer_contest.performance')),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='performance_run_state', to='singer_contest.contestround')),
            ],
            options={
                'base_manager_name': 'objects',
                'indexes': [models.Index(fields=['state', 'context_version'], name='judge_perf_run_state_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='roundpanelsnapshot',
            index=models.Index(fields=['round', 'state'], name='judge_panel_snapshot_state_idx'),
        ),
        migrations.AddIndex(
            model_name='roundpanelsnapshot',
            index=models.Index(fields=['activity', 'state'], name='judge_panel_activity_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='roundpanelsnapshot',
            constraint=models.UniqueConstraint(fields=('round', 'version'), name='judge_panel_snapshot_round_version'),
        ),
        migrations.AddConstraint(
            model_name='roundpanelsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('expected_judge_count__gte', 1)), name='judge_panel_snapshot_expected_positive'),
        ),
        migrations.AddConstraint(
            model_name='roundpanelsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_judge_count__gte', 1), ('minimum_judge_count__lte', models.F('expected_judge_count'))), name='judge_panel_snapshot_minimum_valid'),
        ),
        migrations.AddIndex(
            model_name='judgesession',
            index=models.Index(fields=['expires_at'], name='judge_session_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='judgesession',
            index=models.Index(fields=['state'], name='judge_session_state_idx'),
        ),
        migrations.AddIndex(
            model_name='judgeseatgrant',
            index=models.Index(fields=['seat'], name='judge_seat_grant_seat_idx'),
        ),
        migrations.AddConstraint(
            model_name='roundpanelsnapshotmember',
            constraint=models.UniqueConstraint(fields=('panel_snapshot', 'seat_key'), name='judge_panel_member_seat_key'),
        ),
        migrations.AddConstraint(
            model_name='roundpanelsnapshotmember',
            constraint=models.UniqueConstraint(fields=('panel_snapshot', 'judge'), name='judge_panel_member_judge'),
        ),
        migrations.AddIndex(
            model_name='judgeseat',
            index=models.Index(fields=['state'], name='judge_seat_state_idx'),
        ),
    ]
