# Generated by Django 6.0.8 on 2026-09-08 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer_contest', '0034_m2c_judge_authority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scorerecord',
            name='source_command_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='judge_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='score_records', to='singer_contest.judgeseat'),
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='panel_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='score_records', to='singer_contest.roundpanelsnapshot'),
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='source',
            field=models.CharField(choices=[('staff_rapid', 'Staff rapid score'), ('direct_judge', 'Direct judge'), ('staff_proxy', 'Staff proxy'), ('paper_dr', 'Paper disaster recovery'), ('import', 'Approved import')], default='staff_rapid', max_length=16),
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='source_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='JudgeScoreReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.CharField(max_length=64, unique=True)),
                ('operation', models.CharField(max_length=32)),
                ('source', models.CharField(choices=[('staff_rapid', 'Staff rapid score'), ('direct_judge', 'Direct judge'), ('staff_proxy', 'Staff proxy'), ('paper_dr', 'Paper disaster recovery'), ('import', 'Approved import')], max_length=16)),
                ('payload_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded')], default='pending', max_length=16)),
                ('result_code', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='judge_score_receipts', to=settings.AUTH_USER_MODEL)),
                ('panel_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_receipts', to='singer_contest.roundpanelsnapshot')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_receipts', to='singer_contest.performance')),
                ('score_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='judge_receipt', to='singer_contest.scorerecord')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_receipts', to='singer_contest.judgeseat')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='score_receipts', to='singer_contest.judgesession')),
            ],
            options={
                'base_manager_name': 'objects',
                'indexes': [models.Index(fields=['status', 'created_at'], name='judge_receipt_status_idx')],
            },
        ),
    ]
