# Generated by Django 6.0.8 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("singer_contest", "0035_m2c_score_provenance"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestround",
            name="minimum_judge_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="最低有效到场评委数；留空时按准备名单人数 fail-safe。",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="contestround",
            constraint=models.CheckConstraint(
                condition=models.Q(minimum_judge_count__isnull=True)
                | models.Q(minimum_judge_count__gte=1),
                name="round_minimum_judge_positive",
            ),
        ),
    ]
