# Generated by Django 6.0.8 on 2026-09-28 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_retire_unused_phase_and_qr_models'),
        ('singer_contest', '0036_round_minimum_judge_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='singerregistration',
            name='singer_one_registration_per_student_per_activity',
        ),
        migrations.AlterField(
            model_name='singerregistration',
            name='song_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='singerregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('student_id', ''), _negated=True), fields=('activity', 'student_id'), name='singer_one_registration_per_student_per_activity'),
        ),
    ]
