# Generated by Django 6.0.8 on 2026-10-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("singer_contest", "0040_groupstage_group_groupmembership_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="group",
            name="group_unique_order",
        ),
        migrations.RemoveConstraint(
            model_name="group",
            name="group_unique_name",
        ),
        migrations.AddField(
            model_name="group",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("stage", "group_order"),
                name="group_unique_active_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("stage", "name"),
                name="group_unique_active_name",
            ),
        ),
    ]
