# Generated by Django 6.0.8 on 2026-10-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("singer_contest", "0041_remove_group_group_unique_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiencescore",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "未记录"),
                    ("external_form", "外部表单"),
                    ("paper_tally", "纸质统计"),
                    ("manual_other", "其他人工核验"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="audiencescore",
            name="source_note",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
