# Generated by Django 6.0.8 on 2026-10-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("singer_contest", "0042_audiencescore_source_audiencescore_source_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupstage",
            name="material_status",
            field=models.CharField(
                choices=[
                    ("open", "开放提交"),
                    ("closed", "已关闭"),
                    ("supplement_only", "仅补交"),
                ],
                default="closed",
                max_length=16,
            ),
        ),
    ]
