# Generated by Django 6.0.8 on 2026-10-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("singer_contest", "0043_groupstage_material_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupstage",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "待录入"),
                    ("confirmed", "已确认"),
                    ("frozen", "已冻结"),
                    ("cancelled", "已取消"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
    ]
