# Generated by Django 6.0.8 on 2026-10-05 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("singer_contest", "0044_alter_groupstage_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupstage",
            name="roster_source",
            field=models.CharField(
                choices=[
                    ("all_approved", "全部审核通过的选手"),
                    ("round_advanced", "指定轮次的晋级选手"),
                ],
                default="all_approved",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="groupstage",
            name="roster_source_round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="group_stages_sourcing",
                to="singer_contest.contestround",
            ),
        ),
    ]
