# Generated by Django 6.0.8 on 2026-08-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivepackage',
            name='is_current',
            field=models.BooleanField(default=True, help_text='是否当前正式归档包'),
        ),
        migrations.AddField(
            model_name='archivepackage',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='同一活动的归档包版本号'),
        ),
    ]
