# Generated by Django 6.0.8 on 2026-08-29 06:57

from django.conf import settings
from django.db import migrations, models


def normalize_archive_versions(apps, schema_editor):
    """Renumber per-activity versions and keep a single current before constraints.

    The `archive_activity` service already maintains `version`/`is_current` under the
    Activity lock, but a hand-inserted or beta row could carry a stale version or a second
    `is_current=True`. Deterministically assign versions 1..n by pk and mark only the newest
    as current so the new UNIQUE / one-current constraints hold on any existing data.
    """
    ArchivePackage = apps.get_model("archive", "ArchivePackage")
    activity_ids = ArchivePackage.objects.values_list("activity_id", flat=True).distinct()
    for activity_id in activity_ids:
        pks = list(
            ArchivePackage.objects.filter(activity_id=activity_id)
            .order_by("pk")
            .values_list("pk", flat=True)
        )
        for version, pk in enumerate(pks, start=1):
            ArchivePackage.objects.filter(pk=pk).update(
                is_current=pk == pks[-1], version=version
            )


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_archivepackage_is_current_archivepackage_version'),
        ('core', '0004_alter_activity_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(normalize_archive_versions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='archivepackage',
            constraint=models.UniqueConstraint(fields=('activity', 'version'), name='archive_unique_version_per_activity'),
        ),
        migrations.AddConstraint(
            model_name='archivepackage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('activity',), name='archive_one_current_per_activity'),
        ),
    ]
