# Generated by Django 6.0.8 on 2026-10-08 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_archivepackage_archive_unique_version_per_activity_and_more'),
        ('core', '0012_backfill_public_codes_again'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='archivepackage',
            index=models.Index(fields=['file'], name='archivepackage_file_idx'),
        ),
    ]
