# Generated by Django 6.0.6 on 2026-06-23 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farewell_show", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="submissions/%Y/%m/")),
                ("original_name", models.CharField(max_length=255)),
                ("file_size", models.IntegerField()),
                (
                    "file_purpose",
                    models.CharField(
                        choices=[
                            ("accompaniment", "伴奏"),
                            ("background_video", "背景视频"),
                            ("performance_video", "演唱视频"),
                            ("program_image", "节目图片"),
                            ("lyrics_script", "歌词/台词"),
                            ("host_material", "主持稿素材"),
                            ("public_image", "公开首页图片"),
                            ("showcase_image", "往届风采图片"),
                            ("other", "其他附件"),
                        ],
                        default="other",
                        max_length=24,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StaffNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_notes",
                        to="farewell_show.program",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
