# Generated by Django 6.0.6 on 2026-06-23 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farewell_show", "0001_initial"),
        ("files", "0001_initial"),
        ("singer_contest", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="staffnote",
            name="singer_registration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_notes",
                to="singer_contest.singerregistration",
            ),
        ),
        migrations.AddField(
            model_name="submissionfile",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="farewell_show.program",
            ),
        ),
        migrations.AddField(
            model_name="submissionfile",
            name="singer_registration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="singer_contest.singerregistration",
            ),
        ),
        migrations.AddField(
            model_name="submissionfile",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
