# Generated by Django 6.0.6 on 2026-06-23 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farewell_show", "0001_initial"),
        ("files", "0002_initial"),
        ("singer_contest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("missing", "未上传"),
                            ("uploaded", "已上传"),
                            ("reviewed", "已审核"),
                        ],
                        default="missing",
                        max_length=12,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_checks",
                        to="farewell_show.program",
                    ),
                ),
                (
                    "singer_registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_checks",
                        to="singer_contest.singerregistration",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
    ]
