# Generated by Django 6.0.6 on 2026-06-23 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("files", "0003_materialcheck"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[("singer", "歌手比赛报名"), ("program", "毕晚节目")],
                        max_length=12,
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                (
                    "file_purpose",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accompaniment", "伴奏"),
                            ("background_video", "背景视频"),
                            ("performance_video", "演唱视频"),
                            ("program_image", "节目图片"),
                            ("lyrics_script", "歌词/台词"),
                            ("host_material", "主持稿素材"),
                            ("public_image", "公开首页图片"),
                            ("showcase_image", "往届风采图片"),
                            ("other", "其他附件"),
                        ],
                        max_length=24,
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_requirements",
                        to="core.activity",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "pk"],
                "unique_together": {("activity", "applies_to", "item_name")},
            },
        ),
    ]
