# Generated by Django 6.0.8 on 2026-08-27 14:14

from django.conf import settings
from django.db import migrations, models
from typing import Any


def normalize_submission_versions(apps, schema_editor):
    SubmissionFile = apps.get_model("files", "SubmissionFile")
    for owner_field in ("singer_registration_id", "program_id"):
        grouped: dict[tuple[int, str], list[int]] = {}
        rows = SubmissionFile.objects.order_by("pk").values_list(
            "pk", owner_field, "file_purpose"
        )
        for pk, owner_id, purpose in rows:
            if owner_id is None:
                continue
            grouped.setdefault((owner_id, purpose), []).append(pk)
        for pks in grouped.values():
            for version, pk in enumerate(pks, start=1):
                SubmissionFile.objects.filter(pk=pk).update(
                    is_current=pk == pks[-1], version=version
                )


class Migration(migrations.Migration):

    dependencies = [
        ('farewell_show', '0002_program_is_test_data'),
        ('files', '0005_submissionfile_is_test_data'),
        ('singer_contest', '0003_award_is_test_data_scorerecord_is_test_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionfile',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='submissionfile',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(normalize_submission_versions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='submissionfile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True), ('singer_registration__isnull', False)), fields=('singer_registration', 'file_purpose'), name='files_one_current_singer_purpose'),
        ),
        migrations.AddConstraint(
            model_name='submissionfile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True), ('program__isnull', False)), fields=('program', 'file_purpose'), name='files_one_current_program_purpose'),
        ),
    ]
