# Generated by Django 6.0.8 on 2026-08-28 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farewell_show', '0002_program_is_test_data'),
        ('files', '0006_submissionfile_is_current_submissionfile_version_and_more'),
        ('singer_contest', '0008_singerregistration_singer_one_registration_per_account_per_activity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='materialcheck',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('singer_registration__isnull', False), ('program__isnull', True)), models.Q(('singer_registration__isnull', True), ('program__isnull', False)), _connector='OR'), name='materialcheck_owner_singer_program_xor'),
        ),
        migrations.AddConstraint(
            model_name='staffnote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('singer_registration__isnull', False), ('program__isnull', True)), models.Q(('singer_registration__isnull', True), ('program__isnull', False)), _connector='OR'), name='staffnote_owner_singer_program_xor'),
        ),
        migrations.AddConstraint(
            model_name='submissionfile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('singer_registration__isnull', False), ('program__isnull', True)), models.Q(('singer_registration__isnull', True), ('program__isnull', False)), _connector='OR'), name='files_owner_singer_program_xor'),
        ),
    ]
