# Generated by Django 6.0.8 on 2026-08-28 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_materialcheck_materialcheck_owner_singer_program_xor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcheck',
            name='review_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='materialcheck',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialcheck',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_material_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialcheck',
            name='status',
            field=models.CharField(choices=[('missing', '未上传'), ('uploaded', '已上传，待审核'), ('approved', '已审核通过'), ('needs_supplement', '需补交')], default='missing', max_length=20),
        ),
    ]
