# Generated by Django 6.0.8 on 2026-08-29 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_activity_options'),
        ('farewell_show', '0002_program_is_test_data'),
        ('files', '0009_materialcheck_unique_singer_program_item'),
        ('singer_contest', '0011_alter_contestround_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('accompaniment', '伴奏'), ('background_video', '背景视频'), ('performance_video', '演唱视频'), ('program_image', '节目图片'), ('lyrics_script', '歌词/台词'), ('host_material', '主持稿素材'), ('other', '其他附件')], max_length=24)),
                ('label', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('sequence', models.IntegerField(default=0)),
                ('is_test_data', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_slots', to='core.activity')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_slots', to='farewell_show.program')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_slots', to='singer_contest.contestround')),
                ('singer_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_slots', to='singer_contest.singerregistration')),
            ],
            options={
                'ordering': ['sequence', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('singer_registration__isnull', True), ('program__isnull', True), _connector='OR'), name='materialslot_owner_not_both')],
            },
        ),
    ]
