# Generated by Django 6.0.8 on 2026-09-27 11:26

from django.db import migrations, models

# The fallback requirement lists the runtime uses when an activity has configured no
# MaterialRequirement for a scope. Kept as literals here on purpose: a migration must not
# import the runtime service (that service may change while this migration is frozen).
_DEFAULT_REQUIREMENTS = {
    "singer": {"基本信息": "", "联系方式": "", "伴奏文件": "accompaniment"},
    "program": {"基本信息": "", "负责人联系方式": "", "伴奏文件": "accompaniment"},
}


def _backfill_file_purpose(apps, schema_editor):
    """Give every existing MaterialCheck its stable file-purpose snapshot.

    Resolution order (§4.3): the owner's activity determines the requirement scope; a
    configured MaterialRequirement for that (activity, applies_to) wins; otherwise the
    scope's default fallback list applies. An item name that matches neither is left empty
    rather than guessed — a check with no purpose simply has no participant upload path
    until staff configure one.
    """
    MaterialCheck = apps.get_model("files", "MaterialCheck")
    MaterialRequirement = apps.get_model("files", "MaterialRequirement")
    SingerRegistration = apps.get_model("singer_contest", "SingerRegistration")
    Program = apps.get_model("farewell_show", "Program")

    mappings: dict[tuple, dict] = {}
    for check in MaterialCheck.objects.all().iterator():
        if check.singer_registration_id:
            applies_to = "singer"
            activity_id = (
                SingerRegistration.objects.filter(pk=check.singer_registration_id)
                .values_list("activity_id", flat=True)
                .first()
            )
        elif check.program_id:
            applies_to = "program"
            activity_id = (
                Program.objects.filter(pk=check.program_id)
                .values_list("activity_id", flat=True)
                .first()
            )
        else:
            continue
        if activity_id is None:
            continue
        cache_key = (activity_id, applies_to)
        if cache_key not in mappings:
            configured = dict(
                MaterialRequirement.objects.filter(
                    activity_id=activity_id, applies_to=applies_to
                ).values_list("item_name", "file_purpose")
            )
            mappings[cache_key] = {
                name: (purpose or "") for name, purpose in configured.items()
            } or _DEFAULT_REQUIREMENTS[applies_to]
        mapping = mappings[cache_key]
        if check.item_name not in mapping:
            continue
        purpose = mapping[check.item_name]
        if purpose == check.file_purpose:
            continue
        check.file_purpose = purpose
        check.save(update_fields=["file_purpose"])


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_materialslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcheck',
            name='file_purpose',
            field=models.CharField(blank=True, choices=[('accompaniment', '伴奏'), ('background_video', '背景视频'), ('performance_video', '演唱视频'), ('program_image', '节目图片'), ('lyrics_script', '歌词/台词'), ('host_material', '主持稿素材'), ('public_image', '公开首页图片'), ('showcase_image', '往届风采图片'), ('other', '其他附件')], default='', help_text='本检查项当前要求的文件用途快照（服务端维护）；非文件项为空。选手上传的用途以此为准，浏览器不得指定。', max_length=24),
        ),
        migrations.RunPython(_backfill_file_purpose, migrations.RunPython.noop),
    ]
