# Generated by Django 6.0.8 on 2026-09-28 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farewell_show', '0002_program_is_test_data'),
        ('files', '0011_materialcheck_file_purpose'),
        ('ruleset', '0017_historical_schidui_template_identity'),
        ('singer_contest', '0037_remove_singerregistration_singer_one_registration_per_student_per_activity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='submissionfile',
            name='files_one_current_singer_purpose',
        ),
        migrations.AddField(
            model_name='materialcheck',
            name='question_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='materialcheck',
            name='source_ruleset_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_checks', to='ruleset.rulesetversion'),
        ),
        migrations.AddField(
            model_name='submissionfile',
            name='question_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='submissionfile',
            name='source_ruleset_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_files', to='ruleset.rulesetversion'),
        ),
        migrations.AddConstraint(
            model_name='submissionfile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True), ('question_key', ''), ('singer_registration__isnull', False)), fields=('singer_registration', 'file_purpose'), name='files_one_current_singer_purpose'),
        ),
        migrations.AddConstraint(
            model_name='submissionfile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True), ('singer_registration__isnull', False), models.Q(('question_key', ''), _negated=True)), fields=('singer_registration', 'question_key'), name='files_one_current_singer_question'),
        ),
    ]
