# Generated by Django 6.0.8 on 2026-09-28 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farewell_show', '0002_program_is_test_data'),
        ('files', '0012_remove_submissionfile_files_one_current_singer_purpose_and_more'),
        ('ruleset', '0017_historical_schidui_template_identity'),
        ('singer_contest', '0037_remove_singerregistration_singer_one_registration_per_student_per_activity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='materialcheck',
            name='materialcheck_unique_singer_item',
        ),
        migrations.AlterField(
            model_name='materialcheck',
            name='status',
            field=models.CharField(choices=[('missing', '未提交'), ('uploaded', '已提交，待审核'), ('approved', '已审核通过'), ('needs_supplement', '需补交')], default='missing', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='materialcheck',
            constraint=models.UniqueConstraint(condition=models.Q(('question_key', ''), ('singer_registration__isnull', False)), fields=('singer_registration', 'item_name'), name='materialcheck_unique_singer_item'),
        ),
        migrations.AddConstraint(
            model_name='materialcheck',
            constraint=models.UniqueConstraint(condition=models.Q(('singer_registration__isnull', False), models.Q(('question_key', ''), _negated=True)), fields=('singer_registration', 'question_key'), name='materialcheck_unique_singer_question'),
        ),
    ]
