# Generated by Django 6.0.8 on 2026-10-04 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_activity_public_code_not_null"),
        ("farewell_show", "0002_program_is_test_data"),
        (
            "files",
            "0013_remove_materialcheck_materialcheck_unique_singer_item_and_more",
        ),
        ("ruleset", "0017_historical_schidui_template_identity"),
        ("singer_contest", "0041_remove_group_group_unique_order_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="materialcheck",
            name="materialcheck_owner_singer_program_xor",
        ),
        migrations.RemoveConstraint(
            model_name="materialslot",
            name="materialslot_owner_not_both",
        ),
        migrations.RemoveConstraint(
            model_name="submissionfile",
            name="files_owner_singer_program_xor",
        ),
        migrations.AddField(
            model_name="materialcheck",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_checks",
                to="singer_contest.group",
            ),
        ),
        migrations.AddField(
            model_name="materialslot",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_slots",
                to="singer_contest.group",
            ),
        ),
        migrations.AddField(
            model_name="submissionfile",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="singer_contest.group",
            ),
        ),
        migrations.AlterField(
            model_name="materialrequirement",
            name="applies_to",
            field=models.CharField(
                choices=[
                    ("singer", "歌手比赛报名"),
                    ("program", "毕晚节目"),
                    ("group", "分组合唱组"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddConstraint(
            model_name="materialcheck",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("singer_registration__isnull", False),
                        ("program__isnull", True),
                        ("group__isnull", True),
                    ),
                    models.Q(
                        ("singer_registration__isnull", True),
                        ("program__isnull", False),
                        ("group__isnull", True),
                    ),
                    models.Q(
                        ("singer_registration__isnull", True),
                        ("program__isnull", True),
                        ("group__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="materialcheck_owner_subject_xor",
            ),
        ),
        migrations.AddConstraint(
            model_name="materialcheck",
            constraint=models.UniqueConstraint(
                condition=models.Q(("group__isnull", False)),
                fields=("group", "item_name"),
                name="materialcheck_unique_group_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="materialslot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("singer_registration__isnull", True), ("program__isnull", True)
                    ),
                    models.Q(
                        ("singer_registration__isnull", False),
                        ("program__isnull", True),
                        ("group__isnull", True),
                    ),
                    models.Q(
                        ("singer_registration__isnull", True),
                        ("program__isnull", False),
                        ("group__isnull", True),
                    ),
                    models.Q(
                        ("singer_registration__isnull", True),
                        ("program__isnull", True),
                        ("group__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="materialslot_owner_subject_xor",
            ),
        ),
        migrations.AddConstraint(
            model_name="submissionfile",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("group__isnull", False), ("is_current", True), ("question_key", "")
                ),
                fields=("group", "file_purpose"),
                name="files_one_current_group_purpose",
            ),
        ),
        migrations.AddConstraint(
            model_name="submissionfile",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("group__isnull", False),
                    ("is_current", True),
                    models.Q(("question_key", ""), _negated=True),
                ),
                fields=("group", "question_key"),
                name="files_one_current_group_question",
            ),
        ),
        migrations.AddConstraint(
            model_name="submissionfile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("singer_registration__isnull", False),
                        ("program__isnull", True),
                        ("group__isnull", True),
                    ),
                    models.Q(
                        ("singer_registration__isnull", True),
                        ("program__isnull", False),
                        ("group__isnull", True),
                    ),
                    models.Q(
                        ("singer_registration__isnull", True),
                        ("program__isnull", True),
                        ("group__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="files_owner_subject_xor",
            ),
        ),
    ]
