# Generated by Django 6.0.8 on 2026-10-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "files",
            "0014_remove_materialcheck_materialcheck_owner_singer_program_xor_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="materialcheck",
            name="required",
            field=models.BooleanField(
                default=True,
                help_text="该检查项是否属于当前正式材料契约；可选问卷题不阻塞 Group READY。",
            ),
        ),
    ]
