# Generated by Django 6.0.8 on 2026-10-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0015_materialcheck_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionfile",
            name="derivative",
            field=models.FileField(blank=True, upload_to="derivatives/%Y/%m/"),
        ),
    ]
