# Generated by Django 6.0.8 on 2026-10-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_submissionfile_derivative'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcheck',
            name='accepted_file_purposes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
