# Generated by Django 6.0.8 on 2026-10-08 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farewell_show', '0002_program_is_test_data'),
        ('files', '0017_materialcheck_accepted_file_purposes'),
        ('ruleset', '0018_contestruleset_group_stage_keys'),
        ('singer_contest', '0046_groupstage_source_roster_fingerprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submissionfile',
            index=models.Index(fields=['file'], name='submissionfile_file_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionfile',
            index=models.Index(fields=['derivative'], name='submissionfile_derivative_idx'),
        ),
    ]
