# Generated by Django 6.0.8 on 2026-09-08 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_activity_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('secret_digest', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('state', models.CharField(choices=[('created', '已创建'), ('issued', '已签发'), ('checked_in', '已检票'), ('void', '已作废'), ('revoked', '已撤销')], default='created', max_length=16)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('is_test_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.activity')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_tickets', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_tickets', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_tickets', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['activity_id', 'batch_reference', 'serial_number', 'pk'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='TicketAccessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('is_test_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_sessions', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['activity', 'state'], name='tickets_activity_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('batch_reference__isnull', False), ('serial_number__isnull', False)), fields=('activity', 'batch_reference', 'serial_number'), name='tickets_unique_activity_inventory'),
        ),
        migrations.AddIndex(
            model_name='ticketaccesssession',
            index=models.Index(fields=['expires_at', 'revoked_at'], name='tickets_session_expiry_idx'),
        ),
    ]
