# Generated by Django 6.0.6 on 2026-06-23 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("farewell_show", "0001_initial"),
        ("singer_contest", "0002_award_contestround_judge_scorerecord_scoresummary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("score_dispute", "分数争议"),
                            ("vote_anomaly", "投票异常"),
                            ("withdrawal", "临时弃赛"),
                            ("equipment_issue", "设备问题"),
                            ("info_error", "信息填写错误"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("resolution", models.TextField(blank=True)),
                ("remark", models.TextField(blank=True)),
                ("is_test", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="core.activity",
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="farewell_show.program",
                    ),
                ),
                (
                    "singer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="singer_contest.singerregistration",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
    ]
