# Generated by Django 6.0.8 on 2026-10-04 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0001_initial"),
        ("singer_contest", "0041_remove_group_group_unique_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentrecord",
            name="authority_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "未记录"),
                    ("active", "进行中（ACTIVE）"),
                    ("hold", "已暂停（HOLD）"),
                    ("locked", "已锁定（LOCKED）"),
                    ("unlocked", "已解锁（UNLOCKED）"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="incidentrecord",
            name="needs_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incidentrecord",
            name="round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidents",
                to="singer_contest.contestround",
            ),
        ),
    ]
