# Generated by Django 6.0.8 on 2026-10-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incidentrecord_authority_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentrecord',
            name='action_taken',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incidentrecord',
            name='problem',
            field=models.TextField(blank=True),
        ),
    ]
